$out_dir = 'build';
$aux_dir = 'build';
$pdflatex = 'lualatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$lualatex = 'lualatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$pdf_mode = 4;
