$pdf_mode = 1;
$pdflatex = 'lualatex -interaction=nonstopmode -halt-on-error -file-line-error -synctex=1 %O %S';
$bibtex = 'bibtex %O %S';
$recorder = 1;

$aux_dir = 'build';
$out_dir = 'build';

@clean_ext = qw(bbl bcf blg run.xml synctex.gz toc lof lot out aux fdb_latexmk fls);
